### PR TITLE
Fixed issues with translated route caching

### LINKED ISSUE #638: Cannot run artisan route:trans:list
I'm using Laravel 5.8 and LaravelLocalization 1.3.19.

When I tried caching my routes and running `php artisan route:trans:list en`, the following error occurred. How can I fix this?

```
ErrorException  : Undefined property: Mcamara\LaravelLocalization\Commands\RouteTranslationsListCommand::$routes

  at C:\myproject\vendor\mcamara\laravel-localization\src\Mcamara\LaravelLocalization\Commands\RouteTranslationsListCommand.php:31
    27|      * Execute the console command.
    28|      */
    29|     public function handle()
    30|     {
  > 31|         if (count($this->routes) == 0) {
    32|             $this->error("Your application doesn't have any routes.");
    33|             return;
    34|         }
    35| 

  Exception trace:

  1   Illuminate\Foundation\Bootstrap\HandleExceptions::handleError("Undefined property: Mcamara\LaravelLocalization\Commands\RouteTranslationsListCommand::$routes", "C:\Users\tester\D
ocuments\projects\myproject\vendor\mcamara\laravel-localization\src\Mcamara\LaravelLocalization\Commands\RouteTranslationsListCommand.php", [])
      C:\myproject\vendor\mcamara\laravel-localization\src\Mcamara\LaravelLocalization\Commands\RouteTranslationsListCommand.php:31

  2   Mcamara\LaravelLocalization\Commands\RouteTranslationsListCommand::handle()
      C:\myproject\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:32

  3   call_user_func_array([])
      C:\myproject\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:32

  4   Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
      C:\myproject\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:90

  5   Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Object(Closure))
      C:\myproject\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:34

  6   Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), [])
      C:\myproject\vendor\laravel\framework\src\Illuminate\Container\Container.php:576

  7   Illuminate\Container\Container::call()
      C:\myproject\vendor\laravel\framework\src\Illuminate\Console\Command.php:183

  8   Illuminate\Console\Command::execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
      C:\myproject\vendor\symfony\console\Command\Command.php:255

  9   Symfony\Component\Console\Command\Command::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
      C:\myproject\vendor\laravel\framework\src\Illuminate\Console\Command.php:170

  10  Illuminate\Console\Command::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      C:\myproject\vendor\symfony\console\Application.php:921

  11  Symfony\Component\Console\Application::doRunCommand(Object(Mcamara\LaravelLocalization\Commands\RouteTranslationsListCommand), Object(Symfony\Component\Console\Input\ArgvInput),
Object(Symfony\Component\Console\Output\ConsoleOutput))
      C:\myproject\vendor\symfony\console\Application.php:273

  12  Symfony\Component\Console\Application::doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      C:\myproject\vendor\symfony\console\Application.php:149

  13  Symfony\Component\Console\Application::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      C:\myproject\vendor\laravel\framework\src\Illuminate\Console\Application.php:90

  14  Illuminate\Console\Application::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      C:\myproject\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php:133

  15  Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      C:\myproject\artisan:37
```

I checked inside `RouteListCommand` and this code is how it retrieve its routes. Is this related to the problem?

```
...
    public function handle()
    {
        if (empty($this->router->getRoutes())) {  //<<<<<<<<<<<
            return $this->error("Your application doesn't have any routes.");
        }

        if (empty($routes = $this->getRoutes())) {
            return $this->error("Your application doesn't have any routes matching the given criteria.");
        }

        $this->displayRoutes($routes);
    }
...
```

### PR DESCRIPTION
**Pull request by czim**
- The list command works again in Laravel 5.8. Also, running applications in console now respects the current locale when routes are cached.
- The cache command is cleaned up.

Fixes #638.

### CODE REVIEW

**Comment by czim** [comment]
Note: the checks have only failed because Travis chokes on the `setUp` return value for PHP 7.0.

**Comment by mcamara** [comment]
Can you please rebase with master? I'll merge it then 😄 
Thanks a lot for your help!

**Comment by czim** [comment]
Rebased!

**Comment by mcamara** [comment]
Thanks a lot for your help, I'll release a new version with your changes!

**Pull request merged**
