### PR TITLE
Sort an array of available locales alphabetically

### PR DESCRIPTION
**Pull request by andrey-helldar**

### CODE REVIEW

**Comment by fisharebest** [comment]
The locales are currently sorted in the order they would be displayed in a language-selector.

This is (mostly) alphabetical order of the native language name.

I say "mostly", as language variants sort under the base language.  i.e. `British English` sorts as `English, British` and `US English` sorts as `English, US`.  Both are found between `Ekegusii` and `español`

This gives an intuitive sort order that allows users to find their own language quickly - especially in a long list of languages.

**Comment by andrey-helldar** [comment]
> This gives an intuitive sort order that allows users to find their own language quickly - especially in a long list of languages.

I do not agree with this statement, because I was not able to intuitively find the necessary localizations in the settings file.

Here's an example: I needed to activate the ru and de locals. Instead of scrolling through the list, found in the `ru` and` de` keys, I had to launch a search on the file and enter `ru` first, and then` de`. It is very uncomfortable.

**Comment by fisharebest** [comment]
> I was not able to intuitively find the necessary localizations in the settings file.

Intuitive for the **user** of the application, not the **developer** of the application...

**Comment by andrey-helldar** [comment]
Maybe you're right, but as a developer it was completely incomprehensible to me.

**Pull request closed without merging**
