### PR TITLE
fix hideDefaultLocaleInURL problem

### PR DESCRIPTION
**Pull request by chadidi**
## You can fix it by going to this file 
`/vendor/mcamara/laravel-localization/src/Mcamara/LaravelLocalization/LaravelLocalization.php`
## and search for 
`$parsed_url[ 'path' ] = $locale . '/' . ltrim($parsed_url[ 'path' ], '/');` 
## you will find something like this

`if ( !empty( $locale ) && ( $locale != $this->defaultLocale || !$this->hideDefaultLocaleInURL() ) )
        {
            $parsed_url[ 'path' ] = $locale . '/' . ltrim($parsed_url[ 'path' ], '/');
        }
        $parsed_url[ 'path' ] = ltrim(ltrim($base_path, '/') . '/' . $parsed_url[ 'path' ], '/');`

## replace the code with this
`$parsed_url[ 'path' ] = $locale . '/' . ltrim(ltrim($base_path, '/') . '/' . $parsed_url[ 'path' ], '/');`

_** Soory for my bad english **_

### CODE REVIEW

**Comment by David-Kurniawan** [comment]
+1

**Comment by David-Kurniawan** [comment]
doesn't work if url like this:
`http://localhost:8000/en/search`
switch to default language, eg: id:
`http://localhost:8000/cari`

**Comment by chadidi** [comment]
### it's working i tested but you can add this instead to check if it's not empty

`if ( !empty( $locale ) )
        {
            $parsed_url[ 'path' ] = $locale . '/' . ltrim(ltrim($base_path, '/') . '/' . $parsed_url[ 'path' ], '/');
        }`

**Comment by David-Kurniawan** [comment]
Nice, now work perfect,,, Thank you

**Comment by sangnguyenplus** [comment]
Hi Chadidi, 
It's not fixed yet, when you change from another locale to default locale, it got error "too many loop redirect".

**Comment by chadidi** [comment]
@sangnguyenplus did it happend to you when you added my code or before cause it's working correctly with me, check your routes and your apache configurations .

**Comment by mcamara** [comment]
Closing this pr as tests haven't been fixed in 4 months.

**Pull request closed without merging**
