### PR TITLE
Fix issue when calling getLocalizedURL() on L5.5

### PR DESCRIPTION
**Pull request by leMaur**
Fix ArrayToString exception when calling getLocalizedURL() without arguments in Laravel 5.5

### CODE REVIEW

**Comment by leMaur** [comment]
Sorry, the commit "ffee670" was not wanted. I went some test/experiment and I made a PR for error.

**Comment by mcamara** [comment]
Thanks for your help, I've added your code to the master branch (and to 1.3.x release)

Thanks again!

**Comment by iwasherefirst2** [comment]
Hey @leMaur, I’m working on v3 and wondering about the purpose of normalizeAttributes(). It seems to set data to null if it's an empty array, but I’m not sure why data would appear in the route parameters at all. How could an array even be passed as a URI parameter?

Do you recall the reason for this? Otherwise, I’d plan to skip it for v3.

**Comment by leMaur** [comment]
> Do you recall the reason for this? Otherwise, I’d plan to skip it for v3.

Hi @iwasherefirst2,
Frankly, I don't recall why I did it.

> How could an array even be passed as a URI parameter?

To answer your question: [RFC 3986: Uniform Resource Identifier \(URI\): Generic Syntax](https://datatracker.ietf.org/doc/html/rfc3986) saying that the query component is a sequence of characters, typically structured as key-value pairs, with values being strings. However, in practice, web development often requires passing lists or arrays through URIs, especially in JSON:APIs, form submissions, and client-server communications. Laravel handles these parameters easily.
E.g. `http://example.com/page-1?page[number]=1&page[size]=25`

**Pull request closed without merging**
