### PR TITLE
Support Laravel < 6 for Illuminate\Support\Env usage

### PR DESCRIPTION
**Pull request by oytuntez**
Fixed `env()` and `Illuminate\Support\Env` usage to support Laravel < 6

### CODE REVIEW

**Comment by 3ffusi0on** [comment]
This is a must needed change as it currently breaks older versions.
Thanks in advance for the merge

**Review by PatrikCo — COMMENTED** [review]
This indeed fixed the error. Thanks. Hope this gets merged upstream asap.

**Comment by iwasherefirst2** [comment]
In my opinion we should just use `env` for all Laravel versions 4- 8. Haven't seen any reason yet not do use the default recommended `env` function.

**Comment by mcamara** [comment]
@oytuntez can you fix the conflicts please? 😄

**Comment by ntold** [comment]
Fixed it for me as well @luntovsky 😎👌

**Comment by oytuntez** [comment]
@mcamara done!

**Comment by mcamara** [comment]
Thanks a lot @oytuntez , I'll merge it and create a new release!

**Pull request merged**
