### PR TITLE
Bugfix

### PR DESCRIPTION
**Pull request by pipisco**
Bug: The required location is not applied if it matches the location of the client.
Result: fixed

### CODE REVIEW

**Comment by iwasherefirst2** [comment]
HI pipisco, can you explain in more detail what exatly is fixed with this commit? Are there any open issues that request a localization switch per domain? And is it possible you accedantily changed the package name to your fork?

**Comment by pipisco** [comment]
> HI pipisco, can you explain in more detail what exatly is fixed with this commit? Are there any open issues that request a localization switch per domain? And is it possible you accedantily changed the package name to your fork?

Hello! You are absolutely right, your package was randomly selected when creating the pull request. In fact, this fix was done for my fork.

**Comment by iwasherefirst2** [comment]
@pipisco  so this can be closed?

**Comment by pipisco** [comment]
> @pipisco so this can be closed?

Yes please. Sorry to mistake.

**Pull request closed without merging**
