### PR TITLE
Add support Laravel 6.*

### PR DESCRIPTION
**Pull request by ahmadmayahi**

### CODE REVIEW

**Comment by ThibaudDauce** [comment]
Laravel is now following semver, you need to add `^6.0` to allow all `6.*` versions.

**Comment by Okipa** [comment]
You may change your PR title to `Add support for Laravel 6.*`.  
=> Laravel 6.2 is ou ;)

**Comment by Okipa** [comment]
You also may change this line https://github.com/mcamara/laravel-localization/blame/master/README.md#L41 to :

```
5.2.0-6.* (PHP 7.1 required) | 1.4.x
```

**Comment by mcamara** [comment]
I'll update the readme file, thanks for your help!

**Pull request merged**
