### PR TITLE
Allow laravel 5.1

### PR DESCRIPTION
**Pull request by nWidart**
Allow laravel 5.1

http://semver.mwl.be/#?package=laravel%2Flaravel&version=~5.0&minimum-stability=stable

### CODE REVIEW

**Comment by nWidart** [comment]
Did you tag this ?

**Comment by nWidart** [comment]
Could you please tag this ? Thank you.

**Comment by mcamara** [comment]
Done, sorry for the delay. I have plenty of work.

**Comment by nWidart** [comment]
Awesome, thank you. No problem at all. :smiley:

**Pull request merged**
