### PR TITLE
The language negotiator will convert the locale names into canonical …

### PR DESCRIPTION
**Pull request by ansata2001**
Improved languageNegotiator, the en-US will match en_US and vice-versa, using the intl extension which has been added to "suggests" of the composer.json.

### CODE REVIEW

**Comment by mcamara** [comment]
Thanks for your commit!

**Comment by erdmenchen** [comment]
Does this also fix #505 ?

**Comment by ansata2001** [comment]
@erdmenchen I don't think so

**Comment by marlongichie** [comment]
Was this fix removed? And if so, is there another solution to get this to work properly?

I'm using `"mcamara/laravel-localization": "^1.3"` and en-US does NOT match en_US as discussed here.

**Comment by ansata2001** [comment]
@marlongichie No it wasn't removed. Do you have the intl extension installed and enabled?

**Comment by ansata2001** [comment]
Not sure if intl is installed by default, I think it's not. And it's not hard to install it and activate.

If you're not up to the intl solution - feel free to implement it the way you like. Laravel is not like to obviously.

Suggestion - check if the intl is up and running. php -i | grep intl from the command line from within the vagrant box.

**Pull request merged**
