### PR TITLE
Update LaravelLocalization.php

### PR DESCRIPTION
**Pull request by lukasfiala**

### CODE REVIEW

**Comment by mcamara** [comment]
Can you provide more information about what your pr fixes? And don't forget to fix the tests!

Thanks!

**Comment by mcamara** [comment]
If you rebase with master, you will fix the errors in your branch.

**Comment by Okipa** [comment]
Any news on this guys ?

**Comment by Okipa** [comment]
Shouldn't this PR change the line 325 from the `LaravelLocalization.php` from `$this->translator->trans($transKeyName, [], $locale)` to `$this->translator->trans($transKeyName, [], null, $locale)` rather than `$this->translator->trans($transKeyName, [], '', $locale)` ?

(Same idea for the line 635).

**Comment by mcamara** [comment]
Hi @Okipa , can you lend me a hand on this please? If you create a PR fixing it I'll merge it into master and create a new version.

Thanks!

**Comment by Okipa** [comment]
After investigations, I think I found the problem, which is not linked to your code but to the readme that is not accurate about which version of the package use with which version of Laravel.
I didn't find the logic but what is sure is that I had to install the version `1.1.*` of your package with Laravel 5.2 to make the routes translations work and not the `1.0.*` one as it is specified.

**Comment by mcamara** [comment]
Closing this PR as it was fixed in the new docs.

**Pull request closed without merging**
