### PR TITLE
Remove middleware interfaces due to deprecation since Laravel 5.1

### PR DESCRIPTION
**Pull request by okaufmann**

### CODE REVIEW

**Comment by mundiir** [comment]
Merge, please!

**Comment by okaufmann** [comment]
In view of a Laravel 5.2 Project this is a bugfix. So it make sense to tag a new release as well.

**Comment by dennisoderwald** [comment]
+1

**Comment by mcamara** [comment]
Thanks! I don't have any computer nearby right now as I'm on holidays, but I will try to merge it in few hours.

Thanks again for your help!

**Comment by mcamara** [comment]
I will tag this release as 1.1

**Comment by dennisoderwald** [comment]
Awesome, thanks @mcamara! :+1:

**Pull request merged**
