### PR TITLE
Added Laravel 6 Support

### PR DESCRIPTION
**Pull request by poldixd**

### CODE REVIEW

**Comment by poldixd** [comment]
Maybe this Pull Request is only for Laravel 6.

In Laravel 6 there are some changes:

- The `Lang::trans` and `Lang::transChoice` methods of the translator have been renamed to `Lang::get` and `Lang::choice`.
- The Helpers are now called via `Illuminate\Support\Str` and `Illuminate\Support\Arr` 

https://laravel.com/docs/6.0/upgrade#helpers

**Comment by dib258** [comment]
Hello @poldixd,

I tried to add the package in my composer.json with your repositories to test it out like this : 

```    
    "require": {
        "php": "^7.2",
        "poldixd/laravel-localization": "dev-patch-1",
    },
    "repositories": [
        {
            "type": "git",
            "url": "https://github.com/poldixd/laravel-localization"
        }
    ]
```

When making a composer install (emptied the cache of composer), I get the following error message : 
```
  Problem 1
    - The requested package poldixd/laravel-localization could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it
```

I think in the constraint of Laravel 6.0, it's php 7.2 minimum and in your PR I think you set the PHP version to 7.1. 

Don't you think this could cause the problem ? 

Thanks in advance ;)

**Comment by poldixd** [comment]
Hi @dib258 , did you add `"minimum-stability": "dev"` to your `composer.json`?

**Comment by jphms** [comment]
@dib258 instead of this:
`"poldixd/laravel-localization": "dev-patch-1",`

replace it with this:
`"mcamara/laravel-localization": "dev-patch-1",`

composer looks for name key, and since the composer.json file has not been changed you should require it like this.

**Comment by mcamara** [comment]
Thanks a lot! I'll merge it and update the readme!

**Pull request merged**
